seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAAACATCGTGCAGG.fastq > data/alt-trim/plate-1-AAACATCG_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAACAACCATGCAGG.fastq > data/alt-trim/plate-1-AACAACCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAACCGAGATGCAGG.fastq > data/alt-trim/plate-1-AACCGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAACGAACGTGCAGG.fastq > data/alt-trim/plate-1-AACGAACG_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAACGCTTATGCAGG.fastq > data/alt-trim/plate-1-AACGCTTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAACGTGATTGCAGG.fastq > data/alt-trim/plate-1-AACGTGAT_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAAGACGGATGCAGG.fastq > data/alt-trim/plate-1-AAGACGGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAAGAGATCTGCAGG.fastq > data/alt-trim/plate-1-AAGAGATC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAAGGACACTGCAGG.fastq > data/alt-trim/plate-1-AAGGACAC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAAGGTACATGCAGG.fastq > data/alt-trim/plate-1-AAGGTACA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAATCCGTCTGCAGG.fastq > data/alt-trim/plate-1-AATCCGTC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAATGTTGCTGCAGG.fastq > data/alt-trim/plate-1-AATGTTGC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACAAGCTATGCAGG.fastq > data/alt-trim/plate-1-ACAAGCTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACACAGAATGCAGG.fastq > data/alt-trim/plate-1-ACACAGAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACACGAGATGCAGG.fastq > data/alt-trim/plate-1-ACACGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACACTGACTGCAGG.fastq > data/alt-trim/plate-1-ACACTGAC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACAGATTCTGCAGG.fastq > data/alt-trim/plate-1-ACAGATTC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACAGCAGATGCAGG.fastq > data/alt-trim/plate-1-ACAGCAGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACATTGGCTGCAGG.fastq > data/alt-trim/plate-1-ACATTGGC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACCACTGTTGCAGG.fastq > data/alt-trim/plate-1-ACCACTGT_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACCTCCAATGCAGG.fastq > data/alt-trim/plate-1-ACCTCCAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACGACAAGTGCAGG.fastq > data/alt-trim/plate-1-ACGACAAG_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACGCTCGATGCAGG.fastq > data/alt-trim/plate-1-ACGCTCGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACGTATCATGCAGG.fastq > data/alt-trim/plate-1-ACGTATCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGACTATGCATGCAGG.fastq > data/alt-trim/plate-1-ACTATGCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGAGTCAATGCAGG.fastq > data/alt-trim/plate-1-AGAGTCAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGATCGCATGCAGG.fastq > data/alt-trim/plate-1-AGATCGCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGATGTACTGCAGG.fastq > data/alt-trim/plate-1-AGATGTAC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGCACCTCTGCAGG.fastq > data/alt-trim/plate-1-AGCACCTC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGCAGGAATGCAGG.fastq > data/alt-trim/plate-1-AGCAGGAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGCCATGCTGCAGG.fastq > data/alt-trim/plate-1-AGCCATGC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGGCTAACTGCAGG.fastq > data/alt-trim/plate-1-AGGCTAAC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGTACAAGTGCAGG.fastq > data/alt-trim/plate-1-AGTACAAG_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGTCAAGCTGCAGG.fastq > data/alt-trim/plate-1-AGTCAAGC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGTCACTATGCAGG.fastq > data/alt-trim/plate-1-AGTCACTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGAGTGGTCATGCAGG.fastq > data/alt-trim/plate-1-AGTGGTCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGATAGCGACTGCAGG.fastq > data/alt-trim/plate-1-ATAGCGAC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGATCCTGTATGCAGG.fastq > data/alt-trim/plate-1-ATCCTGTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGATGCCTAATGCAGG.fastq > data/alt-trim/plate-1-ATGCCTAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGATTGAGGATGCAGG.fastq > data/alt-trim/plate-1-ATTGAGGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGATTGGCTCTGCAGG.fastq > data/alt-trim/plate-1-ATTGGCTC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCAACCACATGCAGG.fastq > data/alt-trim/plate-1-CAACCACA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCAAGACTATGCAGG.fastq > data/alt-trim/plate-1-CAAGACTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCAAGGAGCTGCAGG.fastq > data/alt-trim/plate-1-CAAGGAGC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCAATGGAATGCAGG.fastq > data/alt-trim/plate-1-CAATGGAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCACCTTACTGCAGG.fastq > data/alt-trim/plate-1-CACCTTAC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCACTTCGATGCAGG.fastq > data/alt-trim/plate-1-CACTTCGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCAGATCTGTGCAGG.fastq > data/alt-trim/plate-1-CAGATCTG_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCAGCGTTATGCAGG.fastq > data/alt-trim/plate-1-CAGCGTTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCATACCAATGCAGG.fastq > data/alt-trim/plate-1-CATACCAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCATCAAGTTGCAGG.fastq > data/alt-trim/plate-1-CATCAAGT_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCCAGTTCATGCAGG.fastq > data/alt-trim/plate-1-CCAGTTCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCCATCCTCTGCAGG.fastq > data/alt-trim/plate-1-CCATCCTC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCCGAAGTATGCAGG.fastq > data/alt-trim/plate-1-CCGAAGTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCCGACAACTGCAGG.fastq > data/alt-trim/plate-1-CCGACAAC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCCGTGAGATGCAGG.fastq > data/alt-trim/plate-1-CCGTGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCCTCCTGATGCAGG.fastq > data/alt-trim/plate-1-CCTCCTGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCCTCTATCTGCAGG.fastq > data/alt-trim/plate-1-CCTCTATC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCGAACTTATGCAGG.fastq > data/alt-trim/plate-1-CGAACTTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCGACACACTGCAGG.fastq > data/alt-trim/plate-1-CGACACAC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCGACTGGATGCAGG.fastq > data/alt-trim/plate-1-CGACTGGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCGCATACATGCAGG.fastq > data/alt-trim/plate-1-CGCATACA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCGCTGATCTGCAGG.fastq > data/alt-trim/plate-1-CGCTGATC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCGGATTGCTGCAGG.fastq > data/alt-trim/plate-1-CGGATTGC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCTAAGGTCTGCAGG.fastq > data/alt-trim/plate-1-CTAAGGTC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCTCAATGATGCAGG.fastq > data/alt-trim/plate-1-CTCAATGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCTGAGCCATGCAGG.fastq > data/alt-trim/plate-1-CTGAGCCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGCTGGCATATGCAGG.fastq > data/alt-trim/plate-1-CTGGCATA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGAACAGGCTGCAGG.fastq > data/alt-trim/plate-1-GAACAGGC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGAATCTGATGCAGG.fastq > data/alt-trim/plate-1-GAATCTGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGACAGTGCTGCAGG.fastq > data/alt-trim/plate-1-GACAGTGC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGACTAGTATGCAGG.fastq > data/alt-trim/plate-1-GACTAGTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGAGCTGAATGCAGG.fastq > data/alt-trim/plate-1-GAGCTGAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGAGTTAGCTGCAGG.fastq > data/alt-trim/plate-1-GAGTTAGC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGATAGACATGCAGG.fastq > data/alt-trim/plate-1-GATAGACA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGATGAATCTGCAGG.fastq > data/alt-trim/plate-1-GATGAATC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGCCAAGACTGCAGG.fastq > data/alt-trim/plate-1-GCCAAGAC_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGCCACATATGCAGG.fastq > data/alt-trim/plate-1-GCCACATA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGCGAGTAATGCAGG.fastq > data/alt-trim/plate-1-GCGAGTAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGCTAACGATGCAGG.fastq > data/alt-trim/plate-1-GCTAACGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGCTCGGTATGCAGG.fastq > data/alt-trim/plate-1-GCTCGGTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGGAGAACATGCAGG.fastq > data/alt-trim/plate-1-GGAGAACA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGGTGCGAATGCAGG.fastq > data/alt-trim/plate-1-GGTGCGAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGTACGCAATGCAGG.fastq > data/alt-trim/plate-1-GTACGCAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGTCGTAGATGCAGG.fastq > data/alt-trim/plate-1-GTCGTAGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGTCTGTCATGCAGG.fastq > data/alt-trim/plate-1-GTCTGTCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGGTGTTCTATGCAGG.fastq > data/alt-trim/plate-1-GTGTTCTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGTAGGATGATGCAGG.fastq > data/alt-trim/plate-1-TAGGATGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGTATCAGCATGCAGG.fastq > data/alt-trim/plate-1-TATCAGCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGTCCGTCTATGCAGG.fastq > data/alt-trim/plate-1-TCCGTCTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGTCTTCACATGCAGG.fastq > data/alt-trim/plate-1-TCTTCACA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGTGAAGAGATGCAGG.fastq > data/alt-trim/plate-1-TGAAGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGTGGAACAATGCAGG.fastq > data/alt-trim/plate-1-TGGAACAA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGTGGCTTCATGCAGG.fastq > data/alt-trim/plate-1-TGGCTTCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGTGGTGGTATGCAGG.fastq > data/alt-trim/plate-1-TGGTGGTA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RA_GGTTCACGCATGCAGG.fastq > data/alt-trim/plate-1-TTCACGCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAAACATCGTGCAGG.fastq > data/alt-trim/plate-2-AAACATCG_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAACAACCATGCAGG.fastq > data/alt-trim/plate-2-AACAACCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAACCGAGATGCAGG.fastq > data/alt-trim/plate-2-AACCGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAACGAACGTGCAGG.fastq > data/alt-trim/plate-2-AACGAACG_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAACGCTTATGCAGG.fastq > data/alt-trim/plate-2-AACGCTTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAACGTGATTGCAGG.fastq > data/alt-trim/plate-2-AACGTGAT_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAAGACGGATGCAGG.fastq > data/alt-trim/plate-2-AAGACGGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAAGAGATCTGCAGG.fastq > data/alt-trim/plate-2-AAGAGATC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAAGGACACTGCAGG.fastq > data/alt-trim/plate-2-AAGGACAC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAAGGTACATGCAGG.fastq > data/alt-trim/plate-2-AAGGTACA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAATCCGTCTGCAGG.fastq > data/alt-trim/plate-2-AATCCGTC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAATGTTGCTGCAGG.fastq > data/alt-trim/plate-2-AATGTTGC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACAAGCTATGCAGG.fastq > data/alt-trim/plate-2-ACAAGCTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACACAGAATGCAGG.fastq > data/alt-trim/plate-2-ACACAGAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACACGAGATGCAGG.fastq > data/alt-trim/plate-2-ACACGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACACTGACTGCAGG.fastq > data/alt-trim/plate-2-ACACTGAC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACAGATTCTGCAGG.fastq > data/alt-trim/plate-2-ACAGATTC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACAGCAGATGCAGG.fastq > data/alt-trim/plate-2-ACAGCAGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACATTGGCTGCAGG.fastq > data/alt-trim/plate-2-ACATTGGC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACCACTGTTGCAGG.fastq > data/alt-trim/plate-2-ACCACTGT_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACCTCCAATGCAGG.fastq > data/alt-trim/plate-2-ACCTCCAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACGACAAGTGCAGG.fastq > data/alt-trim/plate-2-ACGACAAG_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACGCTCGATGCAGG.fastq > data/alt-trim/plate-2-ACGCTCGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACGTATCATGCAGG.fastq > data/alt-trim/plate-2-ACGTATCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGACTATGCATGCAGG.fastq > data/alt-trim/plate-2-ACTATGCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGAGTCAATGCAGG.fastq > data/alt-trim/plate-2-AGAGTCAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGATCGCATGCAGG.fastq > data/alt-trim/plate-2-AGATCGCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGATGTACTGCAGG.fastq > data/alt-trim/plate-2-AGATGTAC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGCACCTCTGCAGG.fastq > data/alt-trim/plate-2-AGCACCTC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGCAGGAATGCAGG.fastq > data/alt-trim/plate-2-AGCAGGAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGCCATGCTGCAGG.fastq > data/alt-trim/plate-2-AGCCATGC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGGCTAACTGCAGG.fastq > data/alt-trim/plate-2-AGGCTAAC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGTACAAGTGCAGG.fastq > data/alt-trim/plate-2-AGTACAAG_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGTCAAGCTGCAGG.fastq > data/alt-trim/plate-2-AGTCAAGC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGTCACTATGCAGG.fastq > data/alt-trim/plate-2-AGTCACTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGAGTGGTCATGCAGG.fastq > data/alt-trim/plate-2-AGTGGTCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGATAGCGACTGCAGG.fastq > data/alt-trim/plate-2-ATAGCGAC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGATCCTGTATGCAGG.fastq > data/alt-trim/plate-2-ATCCTGTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGATGCCTAATGCAGG.fastq > data/alt-trim/plate-2-ATGCCTAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGATTGAGGATGCAGG.fastq > data/alt-trim/plate-2-ATTGAGGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGATTGGCTCTGCAGG.fastq > data/alt-trim/plate-2-ATTGGCTC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCAACCACATGCAGG.fastq > data/alt-trim/plate-2-CAACCACA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCAAGACTATGCAGG.fastq > data/alt-trim/plate-2-CAAGACTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCAAGGAGCTGCAGG.fastq > data/alt-trim/plate-2-CAAGGAGC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCAATGGAATGCAGG.fastq > data/alt-trim/plate-2-CAATGGAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCACCTTACTGCAGG.fastq > data/alt-trim/plate-2-CACCTTAC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCACTTCGATGCAGG.fastq > data/alt-trim/plate-2-CACTTCGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCAGATCTGTGCAGG.fastq > data/alt-trim/plate-2-CAGATCTG_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCAGCGTTATGCAGG.fastq > data/alt-trim/plate-2-CAGCGTTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCATACCAATGCAGG.fastq > data/alt-trim/plate-2-CATACCAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCATCAAGTTGCAGG.fastq > data/alt-trim/plate-2-CATCAAGT_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCCAGTTCATGCAGG.fastq > data/alt-trim/plate-2-CCAGTTCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCCATCCTCTGCAGG.fastq > data/alt-trim/plate-2-CCATCCTC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCCGAAGTATGCAGG.fastq > data/alt-trim/plate-2-CCGAAGTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCCGACAACTGCAGG.fastq > data/alt-trim/plate-2-CCGACAAC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCCGTGAGATGCAGG.fastq > data/alt-trim/plate-2-CCGTGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCCTCCTGATGCAGG.fastq > data/alt-trim/plate-2-CCTCCTGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCCTCTATCTGCAGG.fastq > data/alt-trim/plate-2-CCTCTATC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCGAACTTATGCAGG.fastq > data/alt-trim/plate-2-CGAACTTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCGACACACTGCAGG.fastq > data/alt-trim/plate-2-CGACACAC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCGACTGGATGCAGG.fastq > data/alt-trim/plate-2-CGACTGGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCGCATACATGCAGG.fastq > data/alt-trim/plate-2-CGCATACA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCGCTGATCTGCAGG.fastq > data/alt-trim/plate-2-CGCTGATC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCGGATTGCTGCAGG.fastq > data/alt-trim/plate-2-CGGATTGC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCTAAGGTCTGCAGG.fastq > data/alt-trim/plate-2-CTAAGGTC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCTCAATGATGCAGG.fastq > data/alt-trim/plate-2-CTCAATGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCTGAGCCATGCAGG.fastq > data/alt-trim/plate-2-CTGAGCCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGCTGGCATATGCAGG.fastq > data/alt-trim/plate-2-CTGGCATA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGAACAGGCTGCAGG.fastq > data/alt-trim/plate-2-GAACAGGC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGAATCTGATGCAGG.fastq > data/alt-trim/plate-2-GAATCTGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGACAGTGCTGCAGG.fastq > data/alt-trim/plate-2-GACAGTGC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGACTAGTATGCAGG.fastq > data/alt-trim/plate-2-GACTAGTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGAGCTGAATGCAGG.fastq > data/alt-trim/plate-2-GAGCTGAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGAGTTAGCTGCAGG.fastq > data/alt-trim/plate-2-GAGTTAGC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGATAGACATGCAGG.fastq > data/alt-trim/plate-2-GATAGACA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGATGAATCTGCAGG.fastq > data/alt-trim/plate-2-GATGAATC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGCCAAGACTGCAGG.fastq > data/alt-trim/plate-2-GCCAAGAC_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGCCACATATGCAGG.fastq > data/alt-trim/plate-2-GCCACATA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGCGAGTAATGCAGG.fastq > data/alt-trim/plate-2-GCGAGTAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGCTAACGATGCAGG.fastq > data/alt-trim/plate-2-GCTAACGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGCTCGGTATGCAGG.fastq > data/alt-trim/plate-2-GCTCGGTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGGAGAACATGCAGG.fastq > data/alt-trim/plate-2-GGAGAACA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGGTGCGAATGCAGG.fastq > data/alt-trim/plate-2-GGTGCGAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGTACGCAATGCAGG.fastq > data/alt-trim/plate-2-GTACGCAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGTCGTAGATGCAGG.fastq > data/alt-trim/plate-2-GTCGTAGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGTCTGTCATGCAGG.fastq > data/alt-trim/plate-2-GTCTGTCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGGTGTTCTATGCAGG.fastq > data/alt-trim/plate-2-GTGTTCTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGTAGGATGATGCAGG.fastq > data/alt-trim/plate-2-TAGGATGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGTATCAGCATGCAGG.fastq > data/alt-trim/plate-2-TATCAGCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGTCCGTCTATGCAGG.fastq > data/alt-trim/plate-2-TCCGTCTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGTCTTCACATGCAGG.fastq > data/alt-trim/plate-2-TCTTCACA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGTGAAGAGATGCAGG.fastq > data/alt-trim/plate-2-TGAAGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGTGGAACAATGCAGG.fastq > data/alt-trim/plate-2-TGGAACAA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGTGGCTTCATGCAGG.fastq > data/alt-trim/plate-2-TGGCTTCA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGTGGTGGTATGCAGG.fastq > data/alt-trim/plate-2-TGGTGGTA_RA.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RA_GGTTCACGCATGCAGG.fastq > data/alt-trim/plate-2-TTCACGCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAAACATCGTGCAGG.fastq > data/alt-trim/plate-3-AAACATCG_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAACAACCATGCAGG.fastq > data/alt-trim/plate-3-AACAACCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAACCGAGATGCAGG.fastq > data/alt-trim/plate-3-AACCGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAACGAACGTGCAGG.fastq > data/alt-trim/plate-3-AACGAACG_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAACGCTTATGCAGG.fastq > data/alt-trim/plate-3-AACGCTTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAACGTGATTGCAGG.fastq > data/alt-trim/plate-3-AACGTGAT_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAAGACGGATGCAGG.fastq > data/alt-trim/plate-3-AAGACGGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAAGAGATCTGCAGG.fastq > data/alt-trim/plate-3-AAGAGATC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAAGGACACTGCAGG.fastq > data/alt-trim/plate-3-AAGGACAC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAAGGTACATGCAGG.fastq > data/alt-trim/plate-3-AAGGTACA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAATCCGTCTGCAGG.fastq > data/alt-trim/plate-3-AATCCGTC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAATGTTGCTGCAGG.fastq > data/alt-trim/plate-3-AATGTTGC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACAAGCTATGCAGG.fastq > data/alt-trim/plate-3-ACAAGCTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACACAGAATGCAGG.fastq > data/alt-trim/plate-3-ACACAGAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACACGAGATGCAGG.fastq > data/alt-trim/plate-3-ACACGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACACTGACTGCAGG.fastq > data/alt-trim/plate-3-ACACTGAC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACAGATTCTGCAGG.fastq > data/alt-trim/plate-3-ACAGATTC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACAGCAGATGCAGG.fastq > data/alt-trim/plate-3-ACAGCAGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACATTGGCTGCAGG.fastq > data/alt-trim/plate-3-ACATTGGC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACCACTGTTGCAGG.fastq > data/alt-trim/plate-3-ACCACTGT_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACCTCCAATGCAGG.fastq > data/alt-trim/plate-3-ACCTCCAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACGACAAGTGCAGG.fastq > data/alt-trim/plate-3-ACGACAAG_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACGCTCGATGCAGG.fastq > data/alt-trim/plate-3-ACGCTCGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACGTATCATGCAGG.fastq > data/alt-trim/plate-3-ACGTATCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGACTATGCATGCAGG.fastq > data/alt-trim/plate-3-ACTATGCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGAGTCAATGCAGG.fastq > data/alt-trim/plate-3-AGAGTCAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGATCGCATGCAGG.fastq > data/alt-trim/plate-3-AGATCGCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGATGTACTGCAGG.fastq > data/alt-trim/plate-3-AGATGTAC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGCACCTCTGCAGG.fastq > data/alt-trim/plate-3-AGCACCTC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGCAGGAATGCAGG.fastq > data/alt-trim/plate-3-AGCAGGAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGCCATGCTGCAGG.fastq > data/alt-trim/plate-3-AGCCATGC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGGCTAACTGCAGG.fastq > data/alt-trim/plate-3-AGGCTAAC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGTACAAGTGCAGG.fastq > data/alt-trim/plate-3-AGTACAAG_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGTCAAGCTGCAGG.fastq > data/alt-trim/plate-3-AGTCAAGC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGTCACTATGCAGG.fastq > data/alt-trim/plate-3-AGTCACTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGAGTGGTCATGCAGG.fastq > data/alt-trim/plate-3-AGTGGTCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGATAGCGACTGCAGG.fastq > data/alt-trim/plate-3-ATAGCGAC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGATCCTGTATGCAGG.fastq > data/alt-trim/plate-3-ATCCTGTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGATGCCTAATGCAGG.fastq > data/alt-trim/plate-3-ATGCCTAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGATTGAGGATGCAGG.fastq > data/alt-trim/plate-3-ATTGAGGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGATTGGCTCTGCAGG.fastq > data/alt-trim/plate-3-ATTGGCTC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCAACCACATGCAGG.fastq > data/alt-trim/plate-3-CAACCACA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCAAGACTATGCAGG.fastq > data/alt-trim/plate-3-CAAGACTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCAAGGAGCTGCAGG.fastq > data/alt-trim/plate-3-CAAGGAGC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCAATGGAATGCAGG.fastq > data/alt-trim/plate-3-CAATGGAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCACCTTACTGCAGG.fastq > data/alt-trim/plate-3-CACCTTAC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCACTTCGATGCAGG.fastq > data/alt-trim/plate-3-CACTTCGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCAGATCTGTGCAGG.fastq > data/alt-trim/plate-3-CAGATCTG_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCAGCGTTATGCAGG.fastq > data/alt-trim/plate-3-CAGCGTTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCATACCAATGCAGG.fastq > data/alt-trim/plate-3-CATACCAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCATCAAGTTGCAGG.fastq > data/alt-trim/plate-3-CATCAAGT_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCCAGTTCATGCAGG.fastq > data/alt-trim/plate-3-CCAGTTCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCCATCCTCTGCAGG.fastq > data/alt-trim/plate-3-CCATCCTC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCCGAAGTATGCAGG.fastq > data/alt-trim/plate-3-CCGAAGTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCCGACAACTGCAGG.fastq > data/alt-trim/plate-3-CCGACAAC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCCGTGAGATGCAGG.fastq > data/alt-trim/plate-3-CCGTGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCCTCCTGATGCAGG.fastq > data/alt-trim/plate-3-CCTCCTGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCCTCTATCTGCAGG.fastq > data/alt-trim/plate-3-CCTCTATC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCGAACTTATGCAGG.fastq > data/alt-trim/plate-3-CGAACTTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCGACACACTGCAGG.fastq > data/alt-trim/plate-3-CGACACAC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCGACTGGATGCAGG.fastq > data/alt-trim/plate-3-CGACTGGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCGCATACATGCAGG.fastq > data/alt-trim/plate-3-CGCATACA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCGCTGATCTGCAGG.fastq > data/alt-trim/plate-3-CGCTGATC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCGGATTGCTGCAGG.fastq > data/alt-trim/plate-3-CGGATTGC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCTAAGGTCTGCAGG.fastq > data/alt-trim/plate-3-CTAAGGTC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCTCAATGATGCAGG.fastq > data/alt-trim/plate-3-CTCAATGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCTGAGCCATGCAGG.fastq > data/alt-trim/plate-3-CTGAGCCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGCTGGCATATGCAGG.fastq > data/alt-trim/plate-3-CTGGCATA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGAACAGGCTGCAGG.fastq > data/alt-trim/plate-3-GAACAGGC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGAATCTGATGCAGG.fastq > data/alt-trim/plate-3-GAATCTGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGACAGTGCTGCAGG.fastq > data/alt-trim/plate-3-GACAGTGC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGACTAGTATGCAGG.fastq > data/alt-trim/plate-3-GACTAGTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGAGCTGAATGCAGG.fastq > data/alt-trim/plate-3-GAGCTGAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGAGTTAGCTGCAGG.fastq > data/alt-trim/plate-3-GAGTTAGC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGATAGACATGCAGG.fastq > data/alt-trim/plate-3-GATAGACA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGATGAATCTGCAGG.fastq > data/alt-trim/plate-3-GATGAATC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGCCAAGACTGCAGG.fastq > data/alt-trim/plate-3-GCCAAGAC_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGCCACATATGCAGG.fastq > data/alt-trim/plate-3-GCCACATA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGCGAGTAATGCAGG.fastq > data/alt-trim/plate-3-GCGAGTAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGCTAACGATGCAGG.fastq > data/alt-trim/plate-3-GCTAACGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGCTCGGTATGCAGG.fastq > data/alt-trim/plate-3-GCTCGGTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGGAGAACATGCAGG.fastq > data/alt-trim/plate-3-GGAGAACA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGGTGCGAATGCAGG.fastq > data/alt-trim/plate-3-GGTGCGAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGTACGCAATGCAGG.fastq > data/alt-trim/plate-3-GTACGCAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGTCGTAGATGCAGG.fastq > data/alt-trim/plate-3-GTCGTAGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGTCTGTCATGCAGG.fastq > data/alt-trim/plate-3-GTCTGTCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGGTGTTCTATGCAGG.fastq > data/alt-trim/plate-3-GTGTTCTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGTAGGATGATGCAGG.fastq > data/alt-trim/plate-3-TAGGATGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGTATCAGCATGCAGG.fastq > data/alt-trim/plate-3-TATCAGCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGTCCGTCTATGCAGG.fastq > data/alt-trim/plate-3-TCCGTCTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGTCTTCACATGCAGG.fastq > data/alt-trim/plate-3-TCTTCACA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGTGAAGAGATGCAGG.fastq > data/alt-trim/plate-3-TGAAGAGA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGTGGAACAATGCAGG.fastq > data/alt-trim/plate-3-TGGAACAA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGTGGCTTCATGCAGG.fastq > data/alt-trim/plate-3-TGGCTTCA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGTGGTGGTATGCAGG.fastq > data/alt-trim/plate-3-TGGTGGTA_RA.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RA_GGTTCACGCATGCAGG.fastq > data/alt-trim/plate-3-TTCACGCA_RA.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAAACATCGTGCAGG.fastq > data/alt-trim/plate-1-AAACATCG_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAACAACCATGCAGG.fastq > data/alt-trim/plate-1-AACAACCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAACCGAGATGCAGG.fastq > data/alt-trim/plate-1-AACCGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAACGAACGTGCAGG.fastq > data/alt-trim/plate-1-AACGAACG_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAACGCTTATGCAGG.fastq > data/alt-trim/plate-1-AACGCTTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAACGTGATTGCAGG.fastq > data/alt-trim/plate-1-AACGTGAT_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAAGACGGATGCAGG.fastq > data/alt-trim/plate-1-AAGACGGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAAGAGATCTGCAGG.fastq > data/alt-trim/plate-1-AAGAGATC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAAGGACACTGCAGG.fastq > data/alt-trim/plate-1-AAGGACAC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAAGGTACATGCAGG.fastq > data/alt-trim/plate-1-AAGGTACA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAATCCGTCTGCAGG.fastq > data/alt-trim/plate-1-AATCCGTC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAATGTTGCTGCAGG.fastq > data/alt-trim/plate-1-AATGTTGC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACAAGCTATGCAGG.fastq > data/alt-trim/plate-1-ACAAGCTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACACAGAATGCAGG.fastq > data/alt-trim/plate-1-ACACAGAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACACGAGATGCAGG.fastq > data/alt-trim/plate-1-ACACGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACACTGACTGCAGG.fastq > data/alt-trim/plate-1-ACACTGAC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACAGATTCTGCAGG.fastq > data/alt-trim/plate-1-ACAGATTC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACAGCAGATGCAGG.fastq > data/alt-trim/plate-1-ACAGCAGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACATTGGCTGCAGG.fastq > data/alt-trim/plate-1-ACATTGGC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACCACTGTTGCAGG.fastq > data/alt-trim/plate-1-ACCACTGT_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACCTCCAATGCAGG.fastq > data/alt-trim/plate-1-ACCTCCAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACGACAAGTGCAGG.fastq > data/alt-trim/plate-1-ACGACAAG_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACGCTCGATGCAGG.fastq > data/alt-trim/plate-1-ACGCTCGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACGTATCATGCAGG.fastq > data/alt-trim/plate-1-ACGTATCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGACTATGCATGCAGG.fastq > data/alt-trim/plate-1-ACTATGCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGAGTCAATGCAGG.fastq > data/alt-trim/plate-1-AGAGTCAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGATCGCATGCAGG.fastq > data/alt-trim/plate-1-AGATCGCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGATGTACTGCAGG.fastq > data/alt-trim/plate-1-AGATGTAC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGCACCTCTGCAGG.fastq > data/alt-trim/plate-1-AGCACCTC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGCAGGAATGCAGG.fastq > data/alt-trim/plate-1-AGCAGGAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGCCATGCTGCAGG.fastq > data/alt-trim/plate-1-AGCCATGC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGGCTAACTGCAGG.fastq > data/alt-trim/plate-1-AGGCTAAC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGTACAAGTGCAGG.fastq > data/alt-trim/plate-1-AGTACAAG_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGTCAAGCTGCAGG.fastq > data/alt-trim/plate-1-AGTCAAGC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGTCACTATGCAGG.fastq > data/alt-trim/plate-1-AGTCACTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGAGTGGTCATGCAGG.fastq > data/alt-trim/plate-1-AGTGGTCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGATAGCGACTGCAGG.fastq > data/alt-trim/plate-1-ATAGCGAC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGATCCTGTATGCAGG.fastq > data/alt-trim/plate-1-ATCCTGTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGATGCCTAATGCAGG.fastq > data/alt-trim/plate-1-ATGCCTAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGATTGAGGATGCAGG.fastq > data/alt-trim/plate-1-ATTGAGGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGATTGGCTCTGCAGG.fastq > data/alt-trim/plate-1-ATTGGCTC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCAACCACATGCAGG.fastq > data/alt-trim/plate-1-CAACCACA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCAAGACTATGCAGG.fastq > data/alt-trim/plate-1-CAAGACTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCAAGGAGCTGCAGG.fastq > data/alt-trim/plate-1-CAAGGAGC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCAATGGAATGCAGG.fastq > data/alt-trim/plate-1-CAATGGAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCACCTTACTGCAGG.fastq > data/alt-trim/plate-1-CACCTTAC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCACTTCGATGCAGG.fastq > data/alt-trim/plate-1-CACTTCGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCAGATCTGTGCAGG.fastq > data/alt-trim/plate-1-CAGATCTG_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCAGCGTTATGCAGG.fastq > data/alt-trim/plate-1-CAGCGTTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCATACCAATGCAGG.fastq > data/alt-trim/plate-1-CATACCAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCATCAAGTTGCAGG.fastq > data/alt-trim/plate-1-CATCAAGT_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCCAGTTCATGCAGG.fastq > data/alt-trim/plate-1-CCAGTTCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCCATCCTCTGCAGG.fastq > data/alt-trim/plate-1-CCATCCTC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCCGAAGTATGCAGG.fastq > data/alt-trim/plate-1-CCGAAGTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCCGACAACTGCAGG.fastq > data/alt-trim/plate-1-CCGACAAC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCCGTGAGATGCAGG.fastq > data/alt-trim/plate-1-CCGTGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCCTCCTGATGCAGG.fastq > data/alt-trim/plate-1-CCTCCTGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCCTCTATCTGCAGG.fastq > data/alt-trim/plate-1-CCTCTATC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCGAACTTATGCAGG.fastq > data/alt-trim/plate-1-CGAACTTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCGACACACTGCAGG.fastq > data/alt-trim/plate-1-CGACACAC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCGACTGGATGCAGG.fastq > data/alt-trim/plate-1-CGACTGGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCGCATACATGCAGG.fastq > data/alt-trim/plate-1-CGCATACA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCGCTGATCTGCAGG.fastq > data/alt-trim/plate-1-CGCTGATC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCGGATTGCTGCAGG.fastq > data/alt-trim/plate-1-CGGATTGC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCTAAGGTCTGCAGG.fastq > data/alt-trim/plate-1-CTAAGGTC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCTCAATGATGCAGG.fastq > data/alt-trim/plate-1-CTCAATGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCTGAGCCATGCAGG.fastq > data/alt-trim/plate-1-CTGAGCCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGCTGGCATATGCAGG.fastq > data/alt-trim/plate-1-CTGGCATA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGAACAGGCTGCAGG.fastq > data/alt-trim/plate-1-GAACAGGC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGAATCTGATGCAGG.fastq > data/alt-trim/plate-1-GAATCTGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGACAGTGCTGCAGG.fastq > data/alt-trim/plate-1-GACAGTGC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGACTAGTATGCAGG.fastq > data/alt-trim/plate-1-GACTAGTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGAGCTGAATGCAGG.fastq > data/alt-trim/plate-1-GAGCTGAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGAGTTAGCTGCAGG.fastq > data/alt-trim/plate-1-GAGTTAGC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGATAGACATGCAGG.fastq > data/alt-trim/plate-1-GATAGACA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGATGAATCTGCAGG.fastq > data/alt-trim/plate-1-GATGAATC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGCCAAGACTGCAGG.fastq > data/alt-trim/plate-1-GCCAAGAC_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGCCACATATGCAGG.fastq > data/alt-trim/plate-1-GCCACATA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGCGAGTAATGCAGG.fastq > data/alt-trim/plate-1-GCGAGTAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGCTAACGATGCAGG.fastq > data/alt-trim/plate-1-GCTAACGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGCTCGGTATGCAGG.fastq > data/alt-trim/plate-1-GCTCGGTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGGAGAACATGCAGG.fastq > data/alt-trim/plate-1-GGAGAACA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGGTGCGAATGCAGG.fastq > data/alt-trim/plate-1-GGTGCGAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGTACGCAATGCAGG.fastq > data/alt-trim/plate-1-GTACGCAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGTCGTAGATGCAGG.fastq > data/alt-trim/plate-1-GTCGTAGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGTCTGTCATGCAGG.fastq > data/alt-trim/plate-1-GTCTGTCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGGTGTTCTATGCAGG.fastq > data/alt-trim/plate-1-GTGTTCTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGTAGGATGATGCAGG.fastq > data/alt-trim/plate-1-TAGGATGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGTATCAGCATGCAGG.fastq > data/alt-trim/plate-1-TATCAGCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGTCCGTCTATGCAGG.fastq > data/alt-trim/plate-1-TCCGTCTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGTCTTCACATGCAGG.fastq > data/alt-trim/plate-1-TCTTCACA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGTGAAGAGATGCAGG.fastq > data/alt-trim/plate-1-TGAAGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGTGGAACAATGCAGG.fastq > data/alt-trim/plate-1-TGGAACAA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGTGGCTTCATGCAGG.fastq > data/alt-trim/plate-1-TGGCTTCA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGTGGTGGTATGCAGG.fastq > data/alt-trim/plate-1-TGGTGGTA_RB.fastq
seqtk trimfq -e 50 data/alt-1/HS2253_AGTCAA_RB_GGTTCACGCATGCAGG.fastq > data/alt-trim/plate-1-TTCACGCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAAACATCGTGCAGG.fastq > data/alt-trim/plate-2-AAACATCG_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAACAACCATGCAGG.fastq > data/alt-trim/plate-2-AACAACCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAACCGAGATGCAGG.fastq > data/alt-trim/plate-2-AACCGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAACGAACGTGCAGG.fastq > data/alt-trim/plate-2-AACGAACG_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAACGCTTATGCAGG.fastq > data/alt-trim/plate-2-AACGCTTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAACGTGATTGCAGG.fastq > data/alt-trim/plate-2-AACGTGAT_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAAGACGGATGCAGG.fastq > data/alt-trim/plate-2-AAGACGGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAAGAGATCTGCAGG.fastq > data/alt-trim/plate-2-AAGAGATC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAAGGACACTGCAGG.fastq > data/alt-trim/plate-2-AAGGACAC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAAGGTACATGCAGG.fastq > data/alt-trim/plate-2-AAGGTACA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAATCCGTCTGCAGG.fastq > data/alt-trim/plate-2-AATCCGTC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAATGTTGCTGCAGG.fastq > data/alt-trim/plate-2-AATGTTGC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACAAGCTATGCAGG.fastq > data/alt-trim/plate-2-ACAAGCTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACACAGAATGCAGG.fastq > data/alt-trim/plate-2-ACACAGAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACACGAGATGCAGG.fastq > data/alt-trim/plate-2-ACACGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACACTGACTGCAGG.fastq > data/alt-trim/plate-2-ACACTGAC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACAGATTCTGCAGG.fastq > data/alt-trim/plate-2-ACAGATTC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACAGCAGATGCAGG.fastq > data/alt-trim/plate-2-ACAGCAGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACATTGGCTGCAGG.fastq > data/alt-trim/plate-2-ACATTGGC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACCACTGTTGCAGG.fastq > data/alt-trim/plate-2-ACCACTGT_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACCTCCAATGCAGG.fastq > data/alt-trim/plate-2-ACCTCCAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACGACAAGTGCAGG.fastq > data/alt-trim/plate-2-ACGACAAG_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACGCTCGATGCAGG.fastq > data/alt-trim/plate-2-ACGCTCGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACGTATCATGCAGG.fastq > data/alt-trim/plate-2-ACGTATCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGACTATGCATGCAGG.fastq > data/alt-trim/plate-2-ACTATGCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGAGTCAATGCAGG.fastq > data/alt-trim/plate-2-AGAGTCAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGATCGCATGCAGG.fastq > data/alt-trim/plate-2-AGATCGCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGATGTACTGCAGG.fastq > data/alt-trim/plate-2-AGATGTAC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGCACCTCTGCAGG.fastq > data/alt-trim/plate-2-AGCACCTC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGCAGGAATGCAGG.fastq > data/alt-trim/plate-2-AGCAGGAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGCCATGCTGCAGG.fastq > data/alt-trim/plate-2-AGCCATGC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGGCTAACTGCAGG.fastq > data/alt-trim/plate-2-AGGCTAAC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGTACAAGTGCAGG.fastq > data/alt-trim/plate-2-AGTACAAG_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGTCAAGCTGCAGG.fastq > data/alt-trim/plate-2-AGTCAAGC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGTCACTATGCAGG.fastq > data/alt-trim/plate-2-AGTCACTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGAGTGGTCATGCAGG.fastq > data/alt-trim/plate-2-AGTGGTCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGATAGCGACTGCAGG.fastq > data/alt-trim/plate-2-ATAGCGAC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGATCCTGTATGCAGG.fastq > data/alt-trim/plate-2-ATCCTGTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGATGCCTAATGCAGG.fastq > data/alt-trim/plate-2-ATGCCTAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGATTGAGGATGCAGG.fastq > data/alt-trim/plate-2-ATTGAGGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGATTGGCTCTGCAGG.fastq > data/alt-trim/plate-2-ATTGGCTC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCAACCACATGCAGG.fastq > data/alt-trim/plate-2-CAACCACA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCAAGACTATGCAGG.fastq > data/alt-trim/plate-2-CAAGACTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCAAGGAGCTGCAGG.fastq > data/alt-trim/plate-2-CAAGGAGC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCAATGGAATGCAGG.fastq > data/alt-trim/plate-2-CAATGGAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCACCTTACTGCAGG.fastq > data/alt-trim/plate-2-CACCTTAC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCACTTCGATGCAGG.fastq > data/alt-trim/plate-2-CACTTCGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCAGATCTGTGCAGG.fastq > data/alt-trim/plate-2-CAGATCTG_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCAGCGTTATGCAGG.fastq > data/alt-trim/plate-2-CAGCGTTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCATACCAATGCAGG.fastq > data/alt-trim/plate-2-CATACCAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCATCAAGTTGCAGG.fastq > data/alt-trim/plate-2-CATCAAGT_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCCAGTTCATGCAGG.fastq > data/alt-trim/plate-2-CCAGTTCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCCATCCTCTGCAGG.fastq > data/alt-trim/plate-2-CCATCCTC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCCGAAGTATGCAGG.fastq > data/alt-trim/plate-2-CCGAAGTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCCGACAACTGCAGG.fastq > data/alt-trim/plate-2-CCGACAAC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCCGTGAGATGCAGG.fastq > data/alt-trim/plate-2-CCGTGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCCTCCTGATGCAGG.fastq > data/alt-trim/plate-2-CCTCCTGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCCTCTATCTGCAGG.fastq > data/alt-trim/plate-2-CCTCTATC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCGAACTTATGCAGG.fastq > data/alt-trim/plate-2-CGAACTTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCGACACACTGCAGG.fastq > data/alt-trim/plate-2-CGACACAC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCGACTGGATGCAGG.fastq > data/alt-trim/plate-2-CGACTGGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCGCATACATGCAGG.fastq > data/alt-trim/plate-2-CGCATACA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCGCTGATCTGCAGG.fastq > data/alt-trim/plate-2-CGCTGATC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCGGATTGCTGCAGG.fastq > data/alt-trim/plate-2-CGGATTGC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCTAAGGTCTGCAGG.fastq > data/alt-trim/plate-2-CTAAGGTC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCTCAATGATGCAGG.fastq > data/alt-trim/plate-2-CTCAATGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCTGAGCCATGCAGG.fastq > data/alt-trim/plate-2-CTGAGCCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGCTGGCATATGCAGG.fastq > data/alt-trim/plate-2-CTGGCATA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGAACAGGCTGCAGG.fastq > data/alt-trim/plate-2-GAACAGGC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGAATCTGATGCAGG.fastq > data/alt-trim/plate-2-GAATCTGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGACAGTGCTGCAGG.fastq > data/alt-trim/plate-2-GACAGTGC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGACTAGTATGCAGG.fastq > data/alt-trim/plate-2-GACTAGTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGAGCTGAATGCAGG.fastq > data/alt-trim/plate-2-GAGCTGAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGAGTTAGCTGCAGG.fastq > data/alt-trim/plate-2-GAGTTAGC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGATAGACATGCAGG.fastq > data/alt-trim/plate-2-GATAGACA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGATGAATCTGCAGG.fastq > data/alt-trim/plate-2-GATGAATC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGCCAAGACTGCAGG.fastq > data/alt-trim/plate-2-GCCAAGAC_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGCCACATATGCAGG.fastq > data/alt-trim/plate-2-GCCACATA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGCGAGTAATGCAGG.fastq > data/alt-trim/plate-2-GCGAGTAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGCTAACGATGCAGG.fastq > data/alt-trim/plate-2-GCTAACGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGCTCGGTATGCAGG.fastq > data/alt-trim/plate-2-GCTCGGTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGGAGAACATGCAGG.fastq > data/alt-trim/plate-2-GGAGAACA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGGTGCGAATGCAGG.fastq > data/alt-trim/plate-2-GGTGCGAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGTACGCAATGCAGG.fastq > data/alt-trim/plate-2-GTACGCAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGTCGTAGATGCAGG.fastq > data/alt-trim/plate-2-GTCGTAGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGTCTGTCATGCAGG.fastq > data/alt-trim/plate-2-GTCTGTCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGGTGTTCTATGCAGG.fastq > data/alt-trim/plate-2-GTGTTCTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGTAGGATGATGCAGG.fastq > data/alt-trim/plate-2-TAGGATGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGTATCAGCATGCAGG.fastq > data/alt-trim/plate-2-TATCAGCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGTCCGTCTATGCAGG.fastq > data/alt-trim/plate-2-TCCGTCTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGTCTTCACATGCAGG.fastq > data/alt-trim/plate-2-TCTTCACA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGTGAAGAGATGCAGG.fastq > data/alt-trim/plate-2-TGAAGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGTGGAACAATGCAGG.fastq > data/alt-trim/plate-2-TGGAACAA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGTGGCTTCATGCAGG.fastq > data/alt-trim/plate-2-TGGCTTCA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGTGGTGGTATGCAGG.fastq > data/alt-trim/plate-2-TGGTGGTA_RB.fastq
seqtk trimfq -e 50 data/alt-2/HS2253_AGTCAA_RB_GGTTCACGCATGCAGG.fastq > data/alt-trim/plate-2-TTCACGCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAAACATCGTGCAGG.fastq > data/alt-trim/plate-3-AAACATCG_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAACAACCATGCAGG.fastq > data/alt-trim/plate-3-AACAACCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAACCGAGATGCAGG.fastq > data/alt-trim/plate-3-AACCGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAACGAACGTGCAGG.fastq > data/alt-trim/plate-3-AACGAACG_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAACGCTTATGCAGG.fastq > data/alt-trim/plate-3-AACGCTTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAACGTGATTGCAGG.fastq > data/alt-trim/plate-3-AACGTGAT_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAAGACGGATGCAGG.fastq > data/alt-trim/plate-3-AAGACGGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAAGAGATCTGCAGG.fastq > data/alt-trim/plate-3-AAGAGATC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAAGGACACTGCAGG.fastq > data/alt-trim/plate-3-AAGGACAC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAAGGTACATGCAGG.fastq > data/alt-trim/plate-3-AAGGTACA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAATCCGTCTGCAGG.fastq > data/alt-trim/plate-3-AATCCGTC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAATGTTGCTGCAGG.fastq > data/alt-trim/plate-3-AATGTTGC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACAAGCTATGCAGG.fastq > data/alt-trim/plate-3-ACAAGCTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACACAGAATGCAGG.fastq > data/alt-trim/plate-3-ACACAGAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACACGAGATGCAGG.fastq > data/alt-trim/plate-3-ACACGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACACTGACTGCAGG.fastq > data/alt-trim/plate-3-ACACTGAC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACAGATTCTGCAGG.fastq > data/alt-trim/plate-3-ACAGATTC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACAGCAGATGCAGG.fastq > data/alt-trim/plate-3-ACAGCAGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACATTGGCTGCAGG.fastq > data/alt-trim/plate-3-ACATTGGC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACCACTGTTGCAGG.fastq > data/alt-trim/plate-3-ACCACTGT_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACCTCCAATGCAGG.fastq > data/alt-trim/plate-3-ACCTCCAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACGACAAGTGCAGG.fastq > data/alt-trim/plate-3-ACGACAAG_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACGCTCGATGCAGG.fastq > data/alt-trim/plate-3-ACGCTCGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACGTATCATGCAGG.fastq > data/alt-trim/plate-3-ACGTATCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGACTATGCATGCAGG.fastq > data/alt-trim/plate-3-ACTATGCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGAGTCAATGCAGG.fastq > data/alt-trim/plate-3-AGAGTCAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGATCGCATGCAGG.fastq > data/alt-trim/plate-3-AGATCGCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGATGTACTGCAGG.fastq > data/alt-trim/plate-3-AGATGTAC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGCACCTCTGCAGG.fastq > data/alt-trim/plate-3-AGCACCTC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGCAGGAATGCAGG.fastq > data/alt-trim/plate-3-AGCAGGAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGCCATGCTGCAGG.fastq > data/alt-trim/plate-3-AGCCATGC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGGCTAACTGCAGG.fastq > data/alt-trim/plate-3-AGGCTAAC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGTACAAGTGCAGG.fastq > data/alt-trim/plate-3-AGTACAAG_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGTCAAGCTGCAGG.fastq > data/alt-trim/plate-3-AGTCAAGC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGTCACTATGCAGG.fastq > data/alt-trim/plate-3-AGTCACTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGAGTGGTCATGCAGG.fastq > data/alt-trim/plate-3-AGTGGTCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGATAGCGACTGCAGG.fastq > data/alt-trim/plate-3-ATAGCGAC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGATCCTGTATGCAGG.fastq > data/alt-trim/plate-3-ATCCTGTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGATGCCTAATGCAGG.fastq > data/alt-trim/plate-3-ATGCCTAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGATTGAGGATGCAGG.fastq > data/alt-trim/plate-3-ATTGAGGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGATTGGCTCTGCAGG.fastq > data/alt-trim/plate-3-ATTGGCTC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCAACCACATGCAGG.fastq > data/alt-trim/plate-3-CAACCACA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCAAGACTATGCAGG.fastq > data/alt-trim/plate-3-CAAGACTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCAAGGAGCTGCAGG.fastq > data/alt-trim/plate-3-CAAGGAGC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCAATGGAATGCAGG.fastq > data/alt-trim/plate-3-CAATGGAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCACCTTACTGCAGG.fastq > data/alt-trim/plate-3-CACCTTAC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCACTTCGATGCAGG.fastq > data/alt-trim/plate-3-CACTTCGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCAGATCTGTGCAGG.fastq > data/alt-trim/plate-3-CAGATCTG_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCAGCGTTATGCAGG.fastq > data/alt-trim/plate-3-CAGCGTTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCATACCAATGCAGG.fastq > data/alt-trim/plate-3-CATACCAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCATCAAGTTGCAGG.fastq > data/alt-trim/plate-3-CATCAAGT_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCCAGTTCATGCAGG.fastq > data/alt-trim/plate-3-CCAGTTCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCCATCCTCTGCAGG.fastq > data/alt-trim/plate-3-CCATCCTC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCCGAAGTATGCAGG.fastq > data/alt-trim/plate-3-CCGAAGTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCCGACAACTGCAGG.fastq > data/alt-trim/plate-3-CCGACAAC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCCGTGAGATGCAGG.fastq > data/alt-trim/plate-3-CCGTGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCCTCCTGATGCAGG.fastq > data/alt-trim/plate-3-CCTCCTGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCCTCTATCTGCAGG.fastq > data/alt-trim/plate-3-CCTCTATC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCGAACTTATGCAGG.fastq > data/alt-trim/plate-3-CGAACTTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCGACACACTGCAGG.fastq > data/alt-trim/plate-3-CGACACAC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCGACTGGATGCAGG.fastq > data/alt-trim/plate-3-CGACTGGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCGCATACATGCAGG.fastq > data/alt-trim/plate-3-CGCATACA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCGCTGATCTGCAGG.fastq > data/alt-trim/plate-3-CGCTGATC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCGGATTGCTGCAGG.fastq > data/alt-trim/plate-3-CGGATTGC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCTAAGGTCTGCAGG.fastq > data/alt-trim/plate-3-CTAAGGTC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCTCAATGATGCAGG.fastq > data/alt-trim/plate-3-CTCAATGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCTGAGCCATGCAGG.fastq > data/alt-trim/plate-3-CTGAGCCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGCTGGCATATGCAGG.fastq > data/alt-trim/plate-3-CTGGCATA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGAACAGGCTGCAGG.fastq > data/alt-trim/plate-3-GAACAGGC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGAATCTGATGCAGG.fastq > data/alt-trim/plate-3-GAATCTGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGACAGTGCTGCAGG.fastq > data/alt-trim/plate-3-GACAGTGC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGACTAGTATGCAGG.fastq > data/alt-trim/plate-3-GACTAGTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGAGCTGAATGCAGG.fastq > data/alt-trim/plate-3-GAGCTGAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGAGTTAGCTGCAGG.fastq > data/alt-trim/plate-3-GAGTTAGC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGATAGACATGCAGG.fastq > data/alt-trim/plate-3-GATAGACA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGATGAATCTGCAGG.fastq > data/alt-trim/plate-3-GATGAATC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGCCAAGACTGCAGG.fastq > data/alt-trim/plate-3-GCCAAGAC_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGCCACATATGCAGG.fastq > data/alt-trim/plate-3-GCCACATA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGCGAGTAATGCAGG.fastq > data/alt-trim/plate-3-GCGAGTAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGCTAACGATGCAGG.fastq > data/alt-trim/plate-3-GCTAACGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGCTCGGTATGCAGG.fastq > data/alt-trim/plate-3-GCTCGGTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGGAGAACATGCAGG.fastq > data/alt-trim/plate-3-GGAGAACA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGGTGCGAATGCAGG.fastq > data/alt-trim/plate-3-GGTGCGAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGTACGCAATGCAGG.fastq > data/alt-trim/plate-3-GTACGCAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGTCGTAGATGCAGG.fastq > data/alt-trim/plate-3-GTCGTAGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGTCTGTCATGCAGG.fastq > data/alt-trim/plate-3-GTCTGTCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGGTGTTCTATGCAGG.fastq > data/alt-trim/plate-3-GTGTTCTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGTAGGATGATGCAGG.fastq > data/alt-trim/plate-3-TAGGATGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGTATCAGCATGCAGG.fastq > data/alt-trim/plate-3-TATCAGCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGTCCGTCTATGCAGG.fastq > data/alt-trim/plate-3-TCCGTCTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGTCTTCACATGCAGG.fastq > data/alt-trim/plate-3-TCTTCACA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGTGAAGAGATGCAGG.fastq > data/alt-trim/plate-3-TGAAGAGA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGTGGAACAATGCAGG.fastq > data/alt-trim/plate-3-TGGAACAA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGTGGCTTCATGCAGG.fastq > data/alt-trim/plate-3-TGGCTTCA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGTGGTGGTATGCAGG.fastq > data/alt-trim/plate-3-TGGTGGTA_RB.fastq
seqtk trimfq -e 50 data/alt-3/HS2253_AGTCAA_RB_GGTTCACGCATGCAGG.fastq > data/alt-trim/plate-3-TTCACGCA_RB.fastq
